# Project
version=1.0
group=com.tristankechlo.crop_marker

# Common
java_version=17
minecraft_version=1.19
version_range=[1.19,1.19.3)
auto_service_version=1.1.1

# Forge
forge_version=41.1.0
forge_loader_range=[41,)

# Fabric
fabric_version=0.58.0+1.19
fabric_loader_version=0.15.11
fabric_loader_min=0.14
fabric_range_min_inclusive=1.19
fabric_range_max_exclusive=1.19.3

# Mod options
mod_name=FullGrownCropMarker
mod_author=Buecher_wurm
mod_id=crop_marker
mod_version=1.2.0
mod_file_name=crop-marker

# Other options
modmenu_version=4.1.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
fabric.loom.multiProjectOptimisation=true
